trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

# 加上這一整段，自動把你在 Library 建好的變數群組帶進來！
variables:
  - group: StaticWebApps-Secrets

steps:
- checkout: self
  submodules: true

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: ''
    azure_static_web_apps_api_token: $(AZURE_DEPLOY_TOKEN)