name: Sync to Azure DevOps

on:
  push:
    branches: [ main ] # 當你每次 push 到 main 分支時觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Azure DevOps
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          git remote add azure https://shfiter:${AZURE_PAT}@dev.azure.com/shfiter/Fategame/_git/Fategame
          git push azure main --force